name: Publish to GH Pages
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the source repository
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: true  # Ensure submodules are fetched

      # Checkout the gh-pages branch (for deployment)
      - name: Checkout destination
        uses: actions/checkout@v3
        if: github.ref == 'refs/heads/main'
        with:
          ref: gh-pages
          path: built-site

      # Setup Hugo with the latest version (v0.118.2)
      - name: Setup Hugo
        run: |
          curl -L -o /tmp/hugo.tar.gz 'https://github.com/gohugoio/hugo/releases/download/v0.118.2/hugo_extended_0.118.2_linux-amd64.tar.gz'
          tar -C ${RUNNER_TEMP} -zxvf /tmp/hugo.tar.gz hugo
          sudo chmod +x ${RUNNER_TEMP}/hugo  # Make Hugo executable

      # Build the Hugo site
      - name: Build
        run: ${RUNNER_TEMP}/hugo --minify  # Ensure Hugo builds the site

      # Deploy the site to gh-pages branch
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          cp -R public/* ${GITHUB_WORKSPACE}/built-site/
          cd ${GITHUB_WORKSPACE}/built-site
          git add .
          git config user.name 'christianvipp'
          git config user.email 'christianvictorr0@gmail.com'
          git commit -m 'Updated site'
          git push

